### ISSUE TITLE
Import to Tasker without removing existing data?

### ISSUE THREAD

**Issue by spacecosmos** [JakobLichterfeld/Tesla_API_in_Tasker#3]
Hi. I wanted to try this out but when I try to import from backup, it says it will overwrite the current settings. Any way of importing the xml-file without doing that?

![SmartSelect_20191009-092852_Tasker](https://user-images.githubusercontent.com/55928670/66460673-aa427280-ea77-11e9-9124-7adeb673961a.jpg)

**Comment by JakobLichterfeld** [comment]
Hi @spacecosmos cool to hear you want to give it a try. I just release [v0.2.0](https://github.com/JakobLichterfeld/Tesla_API_in_Tasker/releases/tag/v0.2.0) which is now tested and comes with more features.
Do you try to import it as described unter installaitons steps: Hold down the Tasker icon in the lower left corner (in your case the house symbol) and then press "import project". (I recommend to to a backup of your data just in case :-) )

**Comment by spacecosmos** [comment]
@JakobLichterfeld - Sorry, I'm either doing something wrong or it doesn't work properly:

![Screenshot_20191009-215108_Tasker](https://user-images.githubusercontent.com/55928670/66515457-74d16f80-eadf-11e9-93e7-3aa0e1caf015.jpg)

![20191009_215340](https://user-images.githubusercontent.com/55928670/66515474-7ac75080-eadf-11e9-8fbc-4d189834748f.jpg)

As I mentioned, I could be doing something wrong here, I'm not too familiar with Tasker.

**Comment by JakobLichterfeld** [comment]
OK, that is strange, just deleted it on my phone and reimport with no issues. Do you have the dependencies installed?

**Comment by JakobLichterfeld** [comment]
Do you want to give the data uri link a try?

taskerproject://H4sIAAAAAAAAAO2d63PjNpLAP8d/BctXs0lqJYtvSV7HVfPwZmbXSXweb6ru7oOKIiGJMxKpJSlPnNo//gC+RJANkrI0kqzp1NaOBTRAvIhHN/rHqwcr/EyCd1ZkSWHw0/m55Dy6P50r51L0+NO5cTG4MM6vz767chYkClz7WpEH8oXcUYYq/eeqlwVTibvA/0TsKM5lSf+Wz6VH8tO5ypJ/d2U7VkSuFcMcDE25r+oDRb3qJYEs2rMW5PqBhHNLen33QXI9KSnXVS+OYSKhTTwSJkKjW3/qeiNW6s6dv1wtr3ppNJOMXCe81gcdQ+7ow46hdvR+x1A6Bg3RO4bRMWig1jFooHnVi4Vp8Xtp+dnfH1lecUXiXOMnlKphGoOhphu6IRerQbLovjnUzb5s6jSa5NEz4k5n0a3lOddd5apX+LmOvfOD6Now1Sw6/h03EW2HtK5e2iRfXCea5dmtf+VxcWKzb6SReV4P5I/oZk4WxEv6iyR/h2mfaXFlv7uazK0pbcmrXvJHHDYl/uJa0TpyxzSVjmKqHZP+rQ71Tp+WOY6N5T5GQZy1FUzXuT640Zxc9WhcRUgRCn1IC0mFVCpkzemgGpz3KpFaGqnIchZbyF/P8/+vv/99IL9981aHC2JkgtUnmOkToLg+EJaW8qpXaO844J4ONKj9laaGl5MW7xtxq+d/Nzb8e2I57G2CGlVJawW1mrputX5fi/+DW00Tt5pek79R7BU5/g8upFnOhGt6Lu6qV2je2uGu8sPdnrv2ZzbvXHeHGm3T9e9CpxjA22B0lH6/Y+paR1MHHf5n8ztBC6c0vhNUqOGVULd7JZL/nv1K1PWLssmrQafhJQkil4TFHqMLyjI8r+Qi1zyh5bCuH3ZaTSbr5kun5VZNt5gWmy5eIKtZ97lU8drEN0q8YsXLFLBelZfIygqsmGZfUYdDcOka0sXZMGVDM561dCkDow+uXeVSbbqMsZ1HeR0TzaMyN4+a0DxKZ0+aYYcVt8P9anxh2UMtbzonCs6n5eWr3faBzY4ynR3p0kVnJtr4mmHSLUS/w4ZkQ+vfdH+x3Hn3tROQMByV5kVw7uRSNEyiUHMcxyQKxQ3KHVWeTG8cN2q5+CV9xHbl5d7S0+7SaXepqtHRZCXuME03Sx1GC7MiIX2AHREnXjh1+jpVQ9v2bkSLPnK95aqpj6tNcyQ9ajyzR1UjT1me48aW/Xka+CvPSXoOfM/SrusqHeh/hT6D+6GXxtXMavC0BsRpNZmWp7L2c1nt+1Pf3JXprFd6TWrnOK39HDcwnjnH3Vlh+MUPnPgFaJreMmGc2bIu0lt2kZ720bMmtsFmExvXpTin4Zx2THOa0X5OU+n7Moj/lTv8z8ZZbRbrINrNaXNihUSauPM50wU++atASrSDbwPi0CK71jyUIl8KmPqRPBLpwf9MvIYpUD+tKfDNKop8D+pPU6TX0IcCrQbc2Yoip90rx71d/N3Y3f7n0TguYVNn//bP+n5TzO36rXIMem6/rY/ufe7oftXjuiIO2rcaQ9O2V2Mkb9j/rqb0dBuyk7+g6/ai02AjNE4a0T/0flWHMdSMgSGroA6jGL3WYbhOfB5xE83CMnCvFSbA/mABr+3I9b2kuHaUDuR+9g75Drk2WPL4L/Gwf0UW9AQzssqnTXDov/LIlxHtmfoXoG65h+IqCoJCnMGrsK96Sa3jtk8nhVLTD3bV9IOv3vTL6lb4xTb7sNLsqqKbtNVgrV0xmm/24TbNHi8Y9a1e1euljdpcSUMuVXIoy4PhcGj2B1Al+7KpDcy+ofNWNVo7tvtIK+lxhsSQRJLte2G01jYmrSDvfPAl7UAfSnf3o8R6OfqdBKHbvAI+yhfqhWDq3u9oLLeGssvWWAXzppaYRdEyvOz1pm40W40vbH/R+4f12R/fuvYsIsGEzJ0ekPUxNp363KaL4vpZS3eTBvO/eCTo0kQXcfKFH/lByNrvGJtGe27T0L0r3SiM3MYZfqAYat+eTGRzoGv2wNT0iWPLQzKwbNkak8lYNy17oA8n2mBCFKJriq2SiarIZn9IJxn9GFtN37LVQmLT41JTy9l91eiTcV+xDFOXabsNdWVIiGkodt+RiTHpW5Y5nowdZTC2JmPDNmxZ08byUBuP1YmlHWPLGUDLKaq54avYWQ+/jrBNgZ270nbNN5TKckgPXGZfM8A1vy8bdN2nJ+9Bv7wcKoLlcEqXw0cyc+05CbdaERVNbrcxKK/CcEPFQUzNFtBNXOD6gRs9/VVhGrZUuvchOVfVaWjqzGfgeafQvTWlM/ghuOFiqeh6XzHojkYttteblefMybrJ0vr/zrQaLJA+MA2jsiSMfrEie3b9l3n0N281n/9lGv2Nnjnz8LJgN3pakutP1qN1MadHuQtaK9ebFlIkAmmyt/7Ki+7JkljRh4gswusJLQW56lXCBfLlp73x/TmxvGoG/FNXQUA8++nWt605KVWtFAkmEVUSkkozeOcuH/w79w8yzytZDKpKCatWkUnT3nh28LSMfgve0XnBXUalelWiBclEdYPl+EwyRTP86DwWTtTwYF4szeLvfrCwol9XizHd7GbtygdCksK2BaTS9D8H/mpJy/ORLK3AohucUh2r8aKEonoKBNNs/uG7dJNVemgayImIsi/Gcgl+twLXGtOhbkWfWICTKElLkWCS+mfxUmkG8RxAwrdWSD54IfFCN3IfSdZ1gtjatMLOrBMv5eh7keV64ev5vFySQowwTWMJyqJ8Tjd/0Pm79NwkDJBrelZBiE99T6bkj9JTkjBArukpBSE+NdMTlwZpMaYqLBpCFZEsqe+RyP1zPWKy36V4cQ04gTRV8sYnb3+p+FwUIC6qQFUmTXxnOffsglJWg/x3KV5YA15gncqhz307o3OHHc0qU0U1XpRQVCGBIJ9NUmv42WkclKDhmUWhLHm8AD74dDXMG7IQVJUSN2dZJksbkIn7R7kqSSAnIix8ITZNcP/zmwf//cffsyLnv0vxwsLyAsVUbJNazDXbtBbi63PNBYqp7mbufO4uw/cr8taf01Wt+IhKZF3K+ofD0ll+luf4i3wp4nukFAkmEfUQJJVlwGY4uoGcW3Zi18prXokQpRDXGJbM81n4j5VaJoGciLBWhdg8QaG85ZyhqohrsX6KoPzrHVCHHmrK26HGbRC8/YlXj+qZqbio1K0mlWWEBbBXfuque5YLA+SE/VkV4lJPp5VBW4ioiNbVoSiRJQzcRV4D9nchXFziPDKV/tf9Ld1nszNimtU6oCwhzLQkkabL3q5fmS9Ne6UGlwzIStRKVZk0se0vLqIv/sQPoqeJvwqsxcU8PqZduF5En3xBmzewLt7c/uv+TXzl/VIqj7ezLHOJ5c7F19bmLNkPS1nyS6m41T7LR/yl1GEH9Q3K+Yy6iRpu8zzSh9Pt1AVbpOduaM8u6Iwa+K5zEcW68Yv7m9ub31//+jD6/fX9h9dvbm8+xm9C8tDXQWA9xTqHc/ZasIiRxcJGG+Yps+Tr5j87z/88p302XxGJVksqhLJH9bZ41vOLqhSLmg6Pc+4nVOQ0ZotiK9sVW42LzY33s3PuJ1dsPmaLYqvbFVuLi02C4OwmCGjB3tLZ6ew3b/4k0fHvzuN32Z2wOz5ScpdO+ou1WP6NPm8c/0FTs8Ob69GKxerS15OIvshxZplkLxeVaHkkujOWrEQ1RzwnZFeISCz+/EbQtmsEPWuERThN2+EXEobW9AU2hZ41Ra8whSRr6qbz0POmr2Tq+7/b8gS6eQHaT6LxzBteZClH9zd3t6/f3oz+efM/H+OlSiquelK+nki8HkZazldT13PpSmZ5NnGdNICVg/5oqEBtIbathWhR2jLDNsUKV+NxrBF3rqNgRRqeWZDeLHPhrmmj9Okzyx15PbaMoa3Iw+5EmUy6uqxp3WFfGXeH1rgvm8bAdOThVa+STJCdqDdgOS6TZCxds83EJ9/yF1PbubBWkR/R6obZTuJD/E/iPsMlA7KqL0tRJjFj9JgdI7XbJJaOOnsjWEzYSqk2pLpgM92jGz1dvE7/oNPlxJ2KvScz26PZwroD2cFMpWjWga70yS1yBm9ZGM0Wtnjiv5RyQ1uTbfd/6MLi+JLnR5L/xZOsNOUTiaQf6FTlRpIbxrEsxApDd0r3xz829EWN8a3iGAlYdqHb5IbQclppOuiWRRvTrudvarStPBq6xaAN1k+uSwvb8gfFYtOE6TkwyUJkow5IuKQnI4HH/Ab1gazkG971eUfGq2nj7bv6Eh/4wpMJG3HNQV8faspzjbivH0lAN3slFUQWyguJplsuOjOpuWTuXKcmfXbqZVdjksCihCjLQmQuPqdbyg8efVauy+TCADmxKa8ilBnkSHRnBXQBis8rufanHAxLCx8HyqV5fGAeN6kFQWbXCdY/qxKi5qqIFCxyv60iGhnvhQELYTEWTlRnx6uIZVmEdAwXXqf4dyFOmGceVxC+9/1IoN+tRAuS1T2vKlc0RCVDFjBacWN5HVJrsqqO6jg4HhXQM5KIimjtMwoSJZskWlVPzapaNkCxkHWkeJhU8rkn4Wpe0f4XIiqiNZlzEllC1ytn7nqFSGF2Lj8f/PeKBOVpLAkrCohyK0R+TXvER3exnJNf2HqcnBoLARURYb+XRbKUfpBMuPxSWA6GpcUPg+TKefyTlJueiwLEhe1WkSkn/m3MmFc1T1wLCJM2Pr0kmWW0WpQfuloUIoXZrnizCWel4DM8rAEj3i1IyXbhUmJr4Fky2CQ22i4lNmjPWPCllK/hZ/HaFV5K3JYOzRM7Mk9YtC1Zi0vJDjFRl4eSP4n1pJO47WP165QegieBv4jDP7EUzEx0aJPFelAcqBY7sWC8dFPAruwhJ2AK0NAUUNLCx+9lPIkXbACFcyMaAE7XACDrhmMYWtcyxuOuPnEG3YFpTrq22p8MJ47eHw+PzgDAhus3YABIqrmtAaC/nYJ0vXo3akhB0ePRkQ62a4gWDWAdac2HzzQ3PBEBea69fh60dGzkhhUzUqSfSdS7JxN64pix91TU0IdzymKlHK1CtgXa1iNLBX3atVY2GhV059qLaUmF+rqlaUndwiylQmap/VQZLDU3o9CZ3HFZkls3TB7gTrIxmsfF4TaPsabx81lYHlgsKI31l8wk4Oc31gMaFb+wQSbDnNnSJ6RDnytNQ92gVtW04XNtSUdzmma+5yPHiqyzd9n/0UMG3eOyk0ZIgkd6IEkUGw5x1gfR9w8PdzT83/TMGl0c+kgd1yHTvoxYh5zdp7+S4+lDVmL2C6zZoc/TcRUSuFb4w4/r4ifM73BdgzSgWImQkYnoQZAFZa1wId1Y9kxKcmQ3AtL47z+Tp8uYefc9u2FIDzOHPkTznTcn3jSaret/m/xm1Q/dP0mmH8nkWbXGTxEJ8fxbOv8K9+8bY6n426o9+m9P6a0d0KFN4PryyOtVNKObjj8tNpdeviFWQIdjuoWMSrg3aCtRQ0euRpniqH4pCmC0adC2cth6mwLdvNjx4led5xqXwBjytqMlELpV0erEANwVgU8M+WJ0jOcG+OR40Os+0Bnu2O+52IwogPdb8H7Ld3i/Be+34P0WQA7vt+D9Frzfgvdbjv1+S7yVw3stu3K7jVvzBd9seel3QnZ1MeYE7oSoJ6kTwzsheCfkGXdC+o4lTzRj0h0bptPV6X9dS3bUrj0eazZRnLEiD/BOyMu9EwLdB9ix5jZVejUoa5+vqhXBaMsfbm6C0TI2+2CgD4wyjFYVwGi/WJ9J8WvGiKFFDC1iaAEpYdUQQ1tQ7COGFjG0qFA+CoUyYmgRQ4sYWsTQIoYWMbSIoS2kRgwtYmgRQ4sYWsTQIoYWMbSIoUUMLVocEUOLGNptMbQ7NjnSXo0q/iFK2eToe3M6p+zMRQSk4O4J5bqFvy2IgT00yvW5frw7cFMHMbItXa5h+Op+hgDkotN2CEC+NG3TgjcIWrprIxFgN0QAdHHfdvIGJ5yNhiL/aeIjGn9iv7/cJ3DrfltzUUprrlbutJ312B58ToW1Ur9araAFBFELiFpA1AKiFo5R3bMJakF5Pmqhl8/FPXbrcsR9lON58IUzpgKkQ7r7QCtzaS2Xc9eOhXuf+Iu1LxvNAB4LTgrN8GyY22mgGUCi25FzEFL9DHIQkIOAHITKM5CDgNdWkYMAZ4ccBOQgIAfhiDgI8VYO733tSE2WtCZyEJCDcPimQA4CchDwVhJyEI79VtKzOAgiaIC2ITTA0BXNUAbsugwPDdAE0ADmw88sKcGTtGBWoh/YO/GfeNcuOWRi0aPSJQv6EbkCyBX47jvkCiBXALkCyBVABe0pKGiRK4BcAeQKIFcAuQLIFUCuQCE1cgWQK4BcAeQKIFcAuQLIFUCuAHIF0IKHXAHkChwZV+DAng4gYeAbcnUAMQfH7usQxNdf0dkBnR2+Q2eH6jPQ2QFtaejsAGeHzg7o7HAKzg6HVlVv5eCQ7N9QA70jDXTanOjigC4Oh28KdHFAFwdUkKKLw7ErSHfyqcc2oE+h9jBWYdXhA1s8H2Ls7VhBm5W0gfyavKS70spCJLo9QT9BXFxLcCdEBmozHHK/kUu6RMSOLGwXHTuRRL70ii4aytb1gpg+++K/QkCdlvxXSD/dSj9fajRwokmP04fRyu/g3UzquDc+5AFBqSpkp2nLxN0C5ayChNaWacHZuWXaw82AUI0RIVzfZntYhw/G8QVHInJ82/bbATi+4BbmxXN8oc3VZuMw+7r4EY3A61dfkvdaUKz2UxAInN9tp6+LusfpB4ThI74Z8c2Ib0Z88xGqivePb7b9xYKWsBcSdmWfqQ9Gi/geHXT43RfO+ZrmWXMGPxa2swhaom8ILTE1Te8P1WEFWqILoCWO7wfSypv79mfEkiCWJNmDIZYEsSSIJUEsCV6lfOlXKRFLglgSxJIglgSxJIglQSxJITViSRBLglgSxJIglgSxJIglQSwJYknw1j1iSRBLsi2W5FtidgjMW8jsAOTE1g1kdiCzA5kdaGh62YYmZHYgswOZHcKkjU9HZgcyO5DZgcwOZHagHhGZHag9RGbH8WoPd8PsgIkCHKSBJkz31JnL2leleIA+5idA8YC8ovdE8YCclttSPCD32Q0pHu98Pwhz944t6wI6vu6J3AF5lbYkd4DUjz3RIhBhsLHPDAj3aEurOBU6x+EIG6dCiwBbFWkRbfvtALQIcKl88bQIaBFHWkQtTOMUaBEgBQNpEUiLQFoE0iKOUEl5OFoEAxCMKifUA5AiqpU6FjhEKxTRi/4clgh/YWyMvxj0NVMdKmX8hVGHv0D4BcIvsmQIv0D4BcIvEH6BdxJf/p1EhF8g/ALhFwi/QPgFwi8QflFIjfALhF8g/ALhFwi/QPgFwi8QfoHwC7y+jvALhF8g/ALhFwi/QPgFwi8QfoGGJoRfIPwC4RcIv0D4xYmqZxF+cWjlGcIvEH6B8AvUHiL84sVoDxF+gfCLlwG/KPh2IPliz32P5AskXyD5AskXu33fkHyB5ItDz/hIvqivF5IvkHyB5AskX7wUDeWByRfIvUDuxXWFe2Fuzr0wh2rf0MvcC1PAvWDWixUVZPZG77P0Q0AH1X/ookW7xSETazWPLlnQj4jFQCxG8vIgFgOxGIjFQCwG3lZ86bcVEYuBWAzEYiAWA7EYiMVALEYhNWIxEIuBWAzEYiAWA7EYiMVALAZiMfBiO2IxEIuxLRbjZdsoW5EvviXyB3i3GckfSP5A8geSP5D88U3Z0pD8geQPJH8IkzY+HckfSP5A8geSP5D8gapSJH+gghTJH8erIN0N+QNyvW4DdljviVoRP1qQFSBH6VMgfkDuxHsifkA+v22JH5BD7IbED96p5RVdOZSvwt/YF/sDcnhqyf6AATstlPSlRgNnG+YadDDV/A5ey6SOe/PvB8Eee+KwnAoXpG3aw01+UI0ReVPfZntYgg/GYQFHInJY2vbbATgs4O7lxXNYQHgZclhqeSUnwGEBneWRw4IcFuSwIIflCPXFh+OwpFqDUaw1OCyLpe74fSxUFhGzpL8xs0TTB0N5oJaZJX0Bs2Tme5/p/wUeQkkQSpJsvhBKglAShJIglAQvUr70i5QIJUEoCUJJEEqCUBKEkiCUpJAaoSQIJUEoCUJJEEqCUBKEkiCUBKEkeOceoSQIJdkWSvItETsE5i0kdgByYusGEjuQ2IHEDjQ0vWxDExI7kNiBxA5h0sanI7EDiR1I7EBiBxI7UI+IxA7UHiKx43i1h7shdsAoAQ7MQBOme+rMV02oT2wkdzyTIXIK5A7IHXpP5A7IW7ktuQPym92Q3FHw7diyIqC76554HZAvaUteB8j62BMjAsEFGzvMgEiPtoyKU2FyHI6rcSqMCLBVkRHRtt8OwIgA18kXz4iAVnBkRNQiNE6BEQGyL5ARgYwIZEQgI+IINZSHY0Sw8+modD49AB+iWqVjoUK0wg+96O9gibgXgxL3YjCU1aGqmvHBH+BeGPKQxg1Vpcy9GAi4F8LTNVIwkIKBFAykYCAFAykYeDnxFC4nIgUDKRhIwUAKBlIwkIKBFIxCaqRgIAUDKRhIwUAKBlIwkIKBFAykYOA9dqRgIAVjWwqG3nyDMbHd3vq0qUbvioSLTYkTLYAbwmeBJm7IfJuRNhS5jrUBx7ahbUBxZtnkXojrt7e+gVdb8TYS3kbC20h4G+kId5xf7TaSTxfEWS++LdR03Wirj81MA4uei1mFLpepZfgsP99fFnQB3An6snTyJgt69Ll8Ff8zshw6bsKzLLvLV9lfx/1Nm0N4mO35+lIrZ7NWULDCZba8/C8cEAZ/q9MotkUhY7lmv9PuhY+PXXY0Ym8p3yqb+tm1dS+DrrDrw6+z+QU/mf0VWzNWpVjzgK7ET1Kw8kJp7tM1zV2QVsUFryq2dItqnCbm1pjMa0uYSOxmTvl3miU3jfTL04i2w2kEdIT7SgOr0XGu6oi8qStdqwkwKkyAj+wqJn2Fn0K6sZpETfPgZO77wQ8/cHMoXUWtiDgjK/orF07+WLp0fh25XvfVw4dfbj7+2BuYuiz/+PwpFHrHdjOFws6FwKuQ1C19F9I6OiPPp0tJfLl1tPTD0E0c8Xb4ZtT2Gf++mOX3ZYdvC7zoNr8uxYHRyn2+bmhs/P30o527VfCTzS3n7mavrmQAZgMzGTzupPBijhQ5HkfHM1YVZXeDFVrHN/Trj4svseJLrPhSXd2kbpedCdP77mmrb8uKUPE7yKhVQq0SapVQq7R/rRK3cj5DtcSlvywpHsrLwwtQK0F7ZKWvNGyuBjJorckGgQrGZls+o+44oDeXGOScnJQiTINOld+oIkyDWUBHpgjToPeopSJMg5Erx3rA0bbgcmlNh6ON1CVaC7BWcgginsOdh74WbksD9YzgZx3SglUHW6GYx/PpB8u2SRhmh338AMQ39QEIeFHBj0HgxyBKOaK/JX4MYh0pzA4/BoEfgziFj0HwGb6cD0NA63n+kYjiTg99mHakGecaFT8YgR+MOHxT4Acj8IMR6GiTeswQmfQng4HR7Rua1tUdW+6OiU66g8mkrw7IWB7K9rE52uAHI9o72miQyX1ThXqjHp1Xkh2fKh286WM0U/filelSyu9QNDXEr366i5TWF6dqh0QNbO/6zl+KaMlZqxg1rdKss9VBGOGRf4p3fd8HtbGojUVtLGpjURuL2ljUxqI2FrWxp6SNXe/zUBe7I11soUlRE4ua2MM3BWpiUROLmljUxH4Tmlh9J1ebi+qvBqUsKHo8KlnwdvORKx85HwjUP6L+EfWPqH9E/SPqH1H/iPpH1D+ekv6Rd5dFFeRuVJB8q6IWErWQh28K1EKiFhK1kKiF/Da0kJC7/jMACzXAj4IKsqQvO0ItJEggOHIt5JpRiCpIVEGiChJVkKiCRBUkqiBRBYkqyFNSQa73eah/3NUnNddNispHVD4evilQ+YjKR1Q+ovLx21A+QgDNjZWPRfVXg/4RFD2az3ToEBP0qwJevfWnv2rKBX52Qm3+OKfnb0sR3eILEm0/IDElUaaO3uVnIjhaAg9MVrQyMXlnuOQdfBQi+cADbZVtP+4AgSZ29O2hqx7boLE/4o0ay4OtLMYwftaV7dCX/FoxzKGsyJrZ1wz22DiQRZM0ui+bmqYPdU2mbxjJo+mEzeSTefvKoyfGvHWkydwKZ9Lcnc4iOp96yWnyahm41wqDXrM/qg0BUhW0ZtjE+rEhiSSbHgWFfZKOnUcruH5FC+EHdJ7+q3LVYwHJKKLi4omghjpRjVrD5AsM+5rSGa1HDHQhXtH1vmIMzb76XNvLGxJGsVKvpBRYh5cFRYtzSSBN9tZfedE9WdKV5UNEFrlBoxIukBduoWDBLJdVEBDPfrqNz9ulqpUiwSSiSkJSaQbv3OWDf+f+QeZ5JYtBVSlh1Soyadobzw6eltFvwTtiB+4yKtWrEi1IJqobLMdncpd+ExN+dB4LJ2p4MC+WZpGcYn5dLcYkyNuVD4QkxYa3qlSa/ufAXy1pedaKV76O1XhRQlE9BYJpNsycRcoPTQM5kTp7GIHyzA1SVvSJBThR/FHyUiSYpP5ZYksVWniKOZ2IhSeOYB+0h8yDaUxVuNZAWBTJkvr0dOz+uR4x2e9SvLgGnECaKnnjU7s2X3wuChAXVaAqkya+s5x7tgnKapD/LsULa8ALrFMxlcHbmcW+BDCrTBXVeFFCUYUEgnw2Sa3hZ6dxUIKGZxaFsuTxAvjg09Uwb8hCUFVK3JxlmSxtQCZu2WyZBnIiwsIXYtME9z+/efDff/w9K3L+uxQvLCwvUEzFNqnFXLNNayG+PtdcoJjqbubO5+4yfL8ib/05XdWKj6hE1qWsfzgsneVneY6/ENyrKEWCSUQ9BEllGbAZjm4g55ZNFsSL8t1FNUKUQlxjWDLPZ+E/VmqZBHIiwloVYvMEhfKWc4aqIq7F+imC8n8VO3W8elTPTMVFpW41qSwjLIC98lN33bNcGCAn7M+qEJd6Oq0M2kJERbSuDkWJLGHgLvIasL8L4eIS55Gp9L/ub+k+m50R06zWAWUJYaYliTQdZz/mv9zWWX8urcN/IO3QZmfW1pdSebydZZlLLHcuvrY2Z8l+WMqSX0rFrTbao3dlj86/vXee/3memKPZlyWlQuihjc788DjnfkJFTmMObSbmxvvZOfeTKzYfc+gPer50E7+2XSPoJ2Ti19HEX7Kzs6VKKq56BUs/r4dBY//JGvvHljG0FXnYnSiTSVeXNa077Cvj7tAa92XTGJiOPDw2Y/9DrGY8eWN/Us0tjf0KZAdrZew/jc+3KgLz1lG7FgXx5XJ0K/rG3IrQlQhdidDQhK5E36ErEboSfeOuRIfW427iPgRQi9gbjerZneGK4uZEVyF0FTp8U6CrELoKofYwVQP2HUueaMakOzZMp6vT/7qW7KhdezzWbKI4Y0UeHJv2EF2FNtAeQnjwkmsDTZjuqTPnCaE+MVZqbeffoEDkJN7DZGsvkqykJQeSsv9I8truyIdEARFIe3H3USBPo5b+PgrkK7Sh7wvv3rFlXSAHpDbN+ES2fzbkB6Rr7doR8tvZT/eDXwDYyFEmcV76mUS9+4Q0xiZD1zk2t5nYbXEVWvz3YJ/lM6NCVpWWr4wKWSTapoU6q21acOZsmfZws9Me5nt+ZPCzvlye9eOJYkeTPtiqG716UxLRwJlrz8Xz10HeN7HNLrfn7cjbk000e3P1BJfK3Y5GYa3Ur1Yr2AN6k3H4xfpMRJ/JPtiM/yV5rwXFaj/bNzs1b93p66LucfqB9iuaNnyuTfxo9IX5hYSzd9n/SdHMimJ1UEiCRxJIic7WIc5aW/j+4eGOhv97RcLo4tAaw7gOmWJ5xDrk7D79legQH7ISs19gzQ6t74urMCOWQ4Lwhx/XxX+fBK1rkAYUKxHSgzrT1rGgrBUupBvLnklJjpIbZvHffyZPl49MIfw9u0O6sLZR9+7k2ijfeXPiTaPZuv63yW9W/dD9k2RK7EyeVWv8FJFwF/c+T0pJKVSybIzg4O8j9+i/PaWX7aN6+RLMbCcLWsJefEQdVY6o0Ip0/XoVzegK96fFptrLN8QK6GgtkinOmBabju/uA63ZpbVczl07Fu594nU2NfuqQpQhjjLFUX3xRm2QXa6Cbl4NtyJR7HjVrE6SjeunyogRz1w/MwBG8i8J2MJyffb/1F7Ym5ThAgA=

**Comment by spacecosmos** [comment]
I'm sorry - but I forgot to install AutoTools. I could import it right away after the installation of AutoTools. That said, not sure how to actually _use_ your tool though. :)

**Comment by JakobLichterfeld** [comment]
Good to hear it works.
You can try it by just running on of the tasks, so for example honk horn. Click on the task and then in the lower left corner on the play symbol. It will then look for a token for your account, did not find one, ask you for your account login data, create a token, delete the temporary stored account data. Afterwards look if your account does have a vehicle assigned ( up to know only first one will work if you have multiple) and then honk the horn in this example.
You can use the task in your own tasks, so in your case in your task to wake TeslaMate you can let honk the horn of your Tesla at the end to get feedback that the wakeup was successful (just add perform task action and give the correct task name use the magnifier symbol for that. U der Task priority add a +1 at the end. This is just one example.

**Comment by spacecosmos** [comment]
Thanks for the info. I get this error though:

![SmartSelect_20191010-084859_Tasker](https://user-images.githubusercontent.com/55928670/66545442-fc989780-eb3a-11e9-8260-48e2c16197d3.jpg)

Also, am I supposed to fill this out?

![SmartSelect_20191010-084924_Tasker](https://user-images.githubusercontent.com/55928670/66545476-11752b00-eb3b-11e9-8970-2740678c51ad.jpg)

**Comment by JakobLichterfeld** [comment]
OK, you do not have a Tasker licence :-) Or a AutoTools one.
The popup is the one I mentioned. To retreive a token for your account you need to provide your tesla account data, which is stored temporaly on your device and will be deleted after retriveing the token.

**Comment by spacecosmos** [comment]
I do have a Tasker license. I bought it through Google Apps.

And where exactly do I fill out the account data? There are many places to write text when opening up the "boxes". :)

**Comment by JakobLichterfeld** [comment]
Do you have an AutoTools licencse? The error message says no :-)
The scene will be automatically displayed when needed, then only e-mail and passwort field will be editable, just as in normal dialogs in windows or something else.

**Comment by spacecosmos** [comment]
> Do you have an AutoTools licencse? The error message says no :-)
> The scene will be automatically displayed when needed, then only e-mail and passwort field will be editable, just as in normal dialogs in windows or something else.

I can't see where I can buy the AutoTools licence? It's an addon for Tasker, but nowhere to actually **buy it**?

**Comment by JakobLichterfeld** [comment]
There is either an additional unlock key in play store or you can buy it as In App purchase, see for example [Tasker FAQs](https://joaoapps.com/faq/)

**Comment by JakobLichterfeld** [comment]
I close this issue, if you need any further help please let me know.
